Enhancement on build/15-dune.sh
AOSC-Dev/autobuild3 pull request #133
Opened 2022-09-09 09:57 UTC by CamberLoid

This PR includes several improvements to build/15-dune.sh, and also fixes a bug of ab_match_archgroup()

PR will be marked ready-for-review after testing.

References:
https://github.com/AOSC-Dev/aosc-os-abbs/pull/4183#discussion_r966587236
https://github.com/AOSC-Dev/wiki/commit/d9b550e0c88a6ec1b59c2214a28f0a96533826d9

2022-09-09 13:30 UTC, CamberLoid commented
Functional on riscv64
```
root@main-96ae0a83 [ / ] # acbs-build ocaml-pp ocaml-csexp
---------------------------------------------- Welcome to ACBS - 20211125 ----------------------------------------------
[INFO]: Searching and resolving dependencies...
[2/2] ocaml-csexp		
[INFO]: Dependencies resolved, 2 packages in the queue
[INFO]: Packages to be built: ocaml-pp, ocaml-csexp
[INFO]: Building ocaml-pp (1/2)...
[INFO]: Fetching required source files...
[INFO]: Fetching source (1/1)...
[INFO]: Computing ('sha256', '5203aa69275c2d8adc3ff6e6c1c2f64abd75c9926eaac92bcf0f131a440719ae') checksum for /var/cache/acbs/tarballs/ca4231d5f5123b1c8c30425e731e50113f8a3edbb804566f60c985478d46f3ba...
[INFO]: Extracting ocaml-pp-1.1.2.tar.gz...
fatal: unsafe repository ('/tree' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /tree
[WARN]: Could not determine tree commit: Command '['git', 'describe', '--always', '--dirty']' returned non-zero exit status 128.
[INFO]: Build log: /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/acbs-build_6699d8l4.log
[INFO]:  Loaded library pm
[INFO]:  Loaded library arch
[INFO]:  Setting $SHELL to /bin/bash ...
[INFO]:  Setting $HOME to /root ...
[INFO]:  Running pre-build QA tests ...
[INFO]:  Pre-build clean up...
[INFO]:  Fixing up ownership in $SRCDIR ...
[INFO]:  Removing SGID bit from $SRCDIR ...
[INFO]:  Parallel build ENABLED
[INFO]:  No executable ‘rustc’ has been found; returned value: 1.
[INFO]:  No executable ‘cargo’ has been found; returned value: 1.
[INFO]:  No executable ‘qmake’ has been found; returned value: 1.
[INFO]:  No executable ‘ruby’ has been found; returned value: 1.
[INFO]:  No executable ‘gem’ has been found; returned value: 1.
[INFO]:  No executable ‘node’ has been found; returned value: 1.
[INFO]:  No executable ‘npm’ has been found; returned value: 1.
[INFO]:  Sourcing environment definition script /etc/profile.d/20-shell.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/25-coreutils.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/40-desktopenvironments.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/bash_completion.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/debuginfod.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/gawk.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/gpm.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/hg.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/perl.sh ...
[INFO]:  Architecture group mainline mismatches ocaml-native: taking false branch.
[INFO]:  Non native code architecture for OCaml detected. Disabling ABSPLITDBG and ABSTRIP ...
[INFO]:  Building Dune project ocaml-pp ...
[INFO]:  Setting dune build target packages: pp
[INFO]:  Installing Dune project ocaml-pp ...
/bin/mkdir: created directory '/var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist'
/bin/mkdir: created directory '/var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr'
/bin/mkdir: created directory '/var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib'
/bin/mkdir: created directory '/var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml'
[INFO]:  Installing component pp ...
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml/pp/META
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml/pp/dune-package
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml/pp/opam
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml/pp/pp.cma
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml/pp/pp.cmi
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml/pp/pp.cmt
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml/pp/pp.cmti
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml/pp/pp.ml
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist//usr/lib/ocaml/pp/pp.mli
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist/usr/doc/pp/CHANGES.md
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist/usr/doc/pp/LICENSE.md
Installing /var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist/usr/doc/pp/README.md
[INFO]:  Correcting directories ...
/bin/mkdir: created directory '/var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist/usr/share'
renamed '/var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist/usr/doc' -> '/var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/abdist/usr/share/doc'
[INFO]:  Loaded library elf
[INFO]:  Loaded library depset
[INFO]:  Running post-build filter: elf ...
[INFO]:  Running post-build filter: infodir ...
[INFO]:  Running post-build filter: infocompress ...
[INFO]:  Running post-build filter: lib_archives ...
[INFO]:  Purging libtool archives from build tree.
[INFO]:  Purging static libraries from build tree.
[INFO]:  Running post-build filter: mancompress ...
[INFO]:  Running post-build filter: perl ...
[INFO]:  Removed perllocal.pod.
[INFO]:  Removed .packlist.
[INFO]:  Running post-build filter: retro_drop_docs ...
[INFO]:  Architecture group mainline mismatches retro: taking false branch.
[INFO]:  Non-Retro architectures detected, skipping retro_drop_docs ...
[INFO]:  Creating empty postinst.
[INFO]:  Creating empty prerm.
[INFO]:  Creating empty postrm.
[INFO]:  Creating empty preinst.
[INFO]:  Running post-build QA tests ...
[INFO]:  Building dpkg package(s) ...
dpkg-deb: building package 'ocaml-pp' in 'ocaml-pp_1.1.2-0_riscv64.deb'.
[INFO]:  Installing dpkg package(s) ...
(Reading database ... 126529 files and directories currently installed.)
Preparing to unpack ocaml-pp_1.1.2-0_riscv64.deb ...
Unpacking ocaml-pp (1.1.2) over (1.1.2) ...
Setting up ocaml-pp (1.1.2) ...
[INFO]:  Archiving package(s) ...
[INFO]:  Using autobuild-aoscarchive as autobuild archiver ...
'/var/cache/acbs/build/acbs.pg7f2xqh/pp-1.1.2/ocaml-pp_1.1.2-0_riscv64.deb' -> '/debs/o/ocaml-pp_1.1.2-0_riscv64.deb'
[INFO]: Building ocaml-csexp (2/2)...
[INFO]: Fetching required source files...
[INFO]: Fetching source (1/1)...
[INFO]: Computing ('sha256', 'd605e4065fa90a58800440ef2f33a2d931398bf2c22061a8acb7df845c0aac02') checksum for /var/cache/acbs/tarballs/4feb113ef77dc92a082b9242c9ddfda3fbae9e990deea6ecf40956356493008f...
[INFO]: Extracting ocaml-csexp-1.5.1.tbz...
fatal: unsafe repository ('/tree' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /tree
[WARN]: Could not determine tree commit: Command '['git', 'describe', '--always', '--dirty']' returned non-zero exit status 128.
[INFO]: Build log: /var/cache/acbs/build/acbs.n06cqbk2/csexp-1.5.1/acbs-build_qbelps2k.log
[INFO]:  Loaded library pm
[INFO]:  Loaded library arch
[INFO]:  Setting $SHELL to /bin/bash ...
[INFO]:  Setting $HOME to /root ...
[INFO]:  Running pre-build QA tests ...
[INFO]:  Pre-build clean up...
[INFO]:  Fixing up ownership in $SRCDIR ...
[INFO]:  Removing SGID bit from $SRCDIR ...
[INFO]:  Parallel build ENABLED
[INFO]:  No executable ‘rustc’ has been found; returned value: 1.
[INFO]:  No executable ‘cargo’ has been found; returned value: 1.
[INFO]:  No executable ‘qmake’ has been found; returned value: 1.
[INFO]:  No executable ‘ruby’ has been found; returned value: 1.
[INFO]:  No executable ‘gem’ has been found; returned value: 1.
[INFO]:  No executable ‘node’ has been found; returned value: 1.
[INFO]:  No executable ‘npm’ has been found; returned value: 1.
[INFO]:  Sourcing environment definition script /etc/profile.d/20-shell.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/25-coreutils.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/40-desktopenvironments.sh ...
[INFO]:  Sourcing environment definition script /etc/profile.d/bash_completion.sh ...
[INFO]:  Sourcing environment definitio [...]

2022-09-09 13:38 UTC, CamberLoid commented
LGTM on amd64
```
root@main-806509a6 [ / ] # acbs-build ocaml-pp ocaml-csexp
---------------------------------------------- Welcome to ACBS - 20211125 ----------------------------------------------
[INFO]: Searching and resolving dependencies...
[2/2] ocaml-csexp		
[INFO]: Dependencies resolved, 2 packages in the queue
[INFO]: Packages to be built: ocaml-pp, ocaml-csexp
[INFO]: Building ocaml-pp (1/2)...
[INFO]: Fetching required source files...
[INFO]: Fetching source (1/1)...
[INFO]: Computing ('sha256', '5203aa69275c2d8adc3ff6e6c1c2f64abd75c9926eaac92bcf0f131a440719ae') checksum for /var/cache/acbs/tarballs/ca4231d5f5123b1c8c30425e731e50113f8a3edbb804566f60c985478d46f3ba...
[INFO]: Extracting ocaml-pp-1.1.2.tar.gz...
[INFO]: Installing dependencies from repository...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  findlib ocaml-csexp ocaml-result
The following NEW packages will be installed:
  dune findlib ocaml ocaml-csexp ocaml-result
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 94.8 MB of archives.
After this operation, 425 MB of additional disk space will be used.
Get:1 https://mirrors.bfsu.edu.cn/anthon/debs stable/main amd64 ocaml amd64 4.09.1 [87.9 MB]
Get:2 https://mirrors.bfsu.edu.cn/anthon/debs stable/main amd64 findlib amd64 1.8.1-5 [949 kB]                         
Get:3 https://mirrors.bfsu.edu.cn/anthon/debs stable/main amd64 ocaml-result amd64 1.5-1 [10.6 kB]                     
Get:4 https://mirrors.bfsu.edu.cn/anthon/debs stable/main amd64 ocaml-csexp amd64 1.3.2-1 [84.9 kB]                    
Get:5 https://mirrors.bfsu.edu.cn/anthon/debs stable/main amd64 dune amd64 2.7.1-1 [5838 kB]                           
Fetched 94.8 MB in 10s (9135 kB/s)                                                                                     
Selecting previously unselected package ocaml.
(Reading database ... 124000 files and directories currently installed.)
Preparing to unpack .../ocaml_4.09.1_amd64.deb ...
Unpacking ocaml (4.09.1) ...
Selecting previously unselected package findlib.
Preparing to unpack .../findlib_1.8.1-5_amd64.deb ...
Unpacking findlib (1.8.1-5) ...
Selecting previously unselected package ocaml-result.
Preparing to unpack .../ocaml-result_1.5-1_amd64.deb ...
Unpacking ocaml-result (1.5-1) ...
Selecting previously unselected package ocaml-csexp.
Preparing to unpack .../ocaml-csexp_1.3.2-1_amd64.deb ...
Unpacking ocaml-csexp (1.3.2-1) ...
Selecting previously unselected package dune.
Preparing to unpack .../dune_2.7.1-1_amd64.deb ...
Unpacking dune (2.7.1-1) ...
Setting up ocaml (4.09.1) ...
Setting up findlib (1.8.1-5) ...
Setting up ocaml-result (1.5-1) ...
Setting up ocaml-csexp (1.3.2-1) ...
Setting up dune (2.7.1-1) ...
fatal: detected dubious ownership in repository at '/tree'
To add an exception for this directory, call:

	git config --global --add safe.directory /tree
[WARN]: Could not determine tree commit: Command '['git', 'describe', '--always', '--dirty']' returned non-zero exit status 128.
[INFO]: Build log: /var/cache/acbs/build/acbs.e2ib5dnb/pp-1.1.2/acbs-build_6deaph8s.log
[INFO]:  Loaded library pm
[INFO]:  Loaded library arch
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `QT_SELECT__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `USECLANG__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGNAME__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGVER__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGDEP__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGDES__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGESS__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGSEC__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGRECOM__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGREL__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGCONFL__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGPROV__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGREP__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGSUG__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `PKGBREAK__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `ABBUILD__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `MTER__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `ABMPM__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `ABAPMS__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `BUILDDEP__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `ABSTRIP__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `ABSPLITDBG__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `SYMTAB__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_SSP__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_SCP__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_RRO__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_NOW__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_FTF__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_SPECS__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_O3__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_OS__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_EXC__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_PIC__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_FLAGS_PIE__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_SAN_ADD__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_SAN_THR__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuild3/lib/arch.sh: line 33: declare: `AB_SAN_LEK__MAINLINE
OCAML-NATIVE': invalid variable name for name reference
/usr/lib/autobuil [...]

2022-09-09 16:08 UTC, CamberLoid commented
> Tested and ready for review

New issue found. Converting to draft now.

2022-09-10 14:09 UTC, MingcongBai commented on build/15-dune.sh
> +	if (! ab_match_archgroup ocaml_native); then
Parentheses probably not necessary (or could even be harmful as you just opened a subshell).

2022-09-10 21:23 UTC, cthbleachbit requested changes

2022-09-10 21:23 UTC, cthbleachbit commented on build/15-dune.sh
> +		abinfo "Non native code architecture for OCaml detected. Disabling ABSPLITDBG and ABSTRIP ..."
Reword:

"OCaml has no native code generation for $ABHOST. Disabling ABSPLITDBG and ABSTRIP..."

2022-09-10 21:23 UTC, cthbleachbit commented on lib/arch.sh
> +					aberr "Refuse to assign ${1} to group-specific variable ${1}__${_GROUP^^}"
Grammar nit: `Refusing to assign ...`

2022-09-10 21:23 UTC, cthbleachbit commented on lib/arch.sh
> +					abinfo "Using ${1}__${ABHOST^^} will suppress the conflict."
Reword: `Use ${1}__${ABHOST^^} instead to suppress the conflict`

2022-09-10 21:23 UTC, cthbleachbit commented on lib/builtins.sh
> +		abwarn "Current ABHOST $ABHOST is not belong to any arch group."
Grammar nit: "does not belong"

2022-09-10 21:23 UTC, cthbleachbit commented on lib/builtins.sh
> +		abwarn "Taking false branch."
Can we be more specific on the action taken? What does a "false" or "true" branch mean here?

2022-09-10 21:23 UTC, cthbleachbit commented on lib/builtins.sh
> +			abinfo "Member '${_grp}' in Architecture group '${ABHOST_GROUP//$'\n'/,}' matches $1: taking true branch."
Same there. Explain action taken by a "true" branch

2022-09-10 21:37 UTC, cthbleachbit requested changes

2022-09-10 21:37 UTC, cthbleachbit commented on lib/builtins.sh
> +	if [[ ! $1 ]]; then
BUG: Is this the right way to check for empty argument? Use `-n` or `-z`.

2022-09-10 21:37 UTC, cthbleachbit commented on lib/builtins.sh
> +		abwarn "Taking false branch."
Maybe print the list of groups containing this arch?

2022-09-11 06:55 UTC, CamberLoid commented on lib/builtins.sh
> +		abwarn "Taking false branch."
> What does a "false" or "true" branch mean here?
As a function only returns 0/true or 1/false, the expression `true/false branch` only means the returning value of the function, for debugging purpose. 

> Can we be more specific on the action taken? 
Won't fix at this time. At current stage of development, printing such traceback message is not that necessary. Also implementing such feature is hard for bash.

> Maybe print the list of groups containing this arch?
It does.

2022-09-11 06:58 UTC, CamberLoid commented on lib/builtins.sh
> +	if [[ ! $1 ]]; then
The expression is valid in bash as manual says.
See https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html#Bash-Conditional-Expressions

> _-n string_
> _string_
> 
>   True if the length of string is non-zero.

2022-09-11 06:58 UTC, CamberLoid commented on lib/builtins.sh
> +			abinfo "Member '${_grp}' in Architecture group '${ABHOST_GROUP//$'\n'/,}' matches $1: taking true branch."
See https://github.com/AOSC-Dev/autobuild3/pull/133#discussion_r967770875

2022-09-11 07:05 UTC, CamberLoid commented on lib/builtins.sh
> +		abwarn "Taking false branch."
FIXME commented.

2022-09-11 07:08 UTC, merged