scriptlet/01-alternatives.sh: bugfix and enhancements
AOSC-Dev/autobuild3 pull request #137
Opened 2022-09-17 19:31 UTC by CamberLoid

* Fixes #136
* Now supports group-specific alternatives file, like arch_loadvar() in lib/arch.sh
* More abinfo/abdbg outputs!

2022-09-17 19:34 UTC, CamberLoid commented
Can personally testify that this fixes issue #136 , and enhancements work in expectation.

2022-09-18 16:53 UTC, cthbleachbit requested changes

2022-09-18 16:53 UTC, cthbleachbit commented on scriptlet/01-alternatives.sh
> +## ${CROSS:-$ARCH} or $ABHOST is always prior than arch groups
Nit: "More specific per-arch alternatives file always take precedence over per-group ones"

2022-09-18 16:53 UTC, cthbleachbit commented on scriptlet/01-alternatives.sh
> +if [ -e "$SRCDIR"/autobuild/alternatives ]; then
Potential correctness issue: Use `[ -f blah ]` instead to check for regular file. Ditto on line 24 and 30.

2022-09-18 16:53 UTC, cthbleachbit commented on scriptlet/01-alternatives.sh
> +				aberr "Refusing to treat autobuild/${_grp}/alternatives as the group-specific alternative file"
Text flow nit: `Refusing to use autobuild/${_grp}/alternatives for group-specific alternatives`

2022-09-18 16:53 UTC, cthbleachbit commented on scriptlet/01-alternatives.sh
> +				abinfo "Create autobuild/${CROSS:-$ARCH}/alternatives instead to suppress the conflict"
Nit: `Create per-arch autobuild/${CROSS:-$ARCH}/alternatives instead to resolve this conflict`

2022-09-18 16:53 UTC, cthbleachbit commented on scriptlet/01-alternatives.sh
> +				aberr "... because there is another file: autobuild/${_assignedGroup}/alternatives"
`... because another file autobuild/${_assignedGroup}/alternatives is also valid for this architecture`

2022-09-18 16:53 UTC, cthbleachbit commented on scriptlet/01-alternatives.sh
> +				abdie "Ambiguous group-specific alternative file detected! Refuse to proceed."
Nit: "Multiple per-group alternative files for this architecture found! Cannot proceed."

2022-09-19 05:56 UTC, cthbleachbit approved these changes

2022-09-19 06:45 UTC, merged